### ISSUE TITLE
g++ and linux-headers in docker base images

### ISSUE THREAD

**Issue by leikoilja** [home-assistant/docker-base#117]
Hi! 
We are [working](https://github.com/leikoilja/glocaltokens/issues/11) on HA custom integration that relies on `grpcio` and `grpcio-tools` python packages and during wheel building, they fail because host OS doesn't have appropriate libraries. With some testing on HomeAssistant `alpine` docker image, it boils down to `g++`and `linux-headers` packages. 

It is possible to SSH to the container and install these packages manually that fixes the wheel building, but it's not at all the right way to do it. Is it possible to include [g++](https://pkgs.alpinelinux.org/package/v3.4/main/x86/g++) and [linux-headers](https://pkgs.alpinelinux.org/package/edge/main/x86/linux-headers) in the `Dockerfile` for base images?

p.s. once i find out some more info about including these packages in base images, i would also ask the same question in HomeAssistant Operating System repo, perhaps being included in [`Dockerfile`](https://github.com/home-assistant/operating-system/blob/dev/Dockerfile)

**Comment by ludeeus** [comment]
If it's just needed to build the wheels, just add the integration here <https://github.com/home-assistant/wheels-custom-integrations>

**Comment by leikoilja** [comment]
Thank you for your reply, @ludeeus.

Wait, so if I add integration there, the action fail to build with "gcc" command related error (and is fixed after installing `g++` and `linux-headers` systemwide), like so: https://github.com/home-assistant/wheels-custom-integrations/runs/1860558838.
That's the reason why i though we need to clear up the questions about `g++` and `linux-headers` here before opening a PR in `wheels-custom-integrations`

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/wheels-custom-integrations/blob/master/requirements.json> add new requirements here

**Comment by leikoilja** [comment]
Oh, that's magical! Makes total sense, thank you, @ludeeus! Closing it
