### ISSUE TITLE
Jemalloc issue on armhf QNAP

### ISSUE THREAD

**Issue by gklank** [home-assistant/docker-base#118]
Hi,

you are using per default the Jemalloc library at least in the "armhf-hassio-audio" and "armhf-hassio-supervisor" images.

This is causing at least on the TS-431X2 a none starting image in the containerstation.

Is it possible to keep this out and make it optional with the "LD_PRELOAD" variable?

Regards,

Gerhard

**Comment by frenck** [comment]
> As jemalloc can cause issues on certain hardware, it can be disabled by passing the environment variable `DISABLE_JEMALLOC` with any value

<https://www.home-assistant.io/installation/linux#optimizations>

**Comment by gklank** [comment]
Hi,

thanks for you help.

Your are right this -e "DISABLE_JEMALLOC=true" is not functioning with the "armhf-hassio-supervisor".

But I am private which makes it not so critical if it is an unsupported installation.
And I have to think about to get it up and running or not using HA.

I want to use several addons for which I need the supervised version - as I understood.
And just to buy another "matching" hardware is the question to invest it or not...


Regards

Gerhard

**Comment by gklank** [comment]
Hi,

sorry for asking, but do you see no chance to keep it vice versa?

To keep the jemalloc library in general out and offer it optionally for using?


Regards

Gerhard

**Comment by frenck** [comment]
Sorry, the supported use cases don't need it.

**Comment by gklank** [comment]
Hi,

I want to ask again - knowing that I may be anoing you...

But I am seeing a lot of users asking the same issue like me.
And as I am understand we are discussing with this library about some performance issues, no functional points.
By changing to "optional" it would be still the same for the ones which can use it.

Therefore I want to ask you to discuss internally about this topic.

You would get a lot more of happy users for using HA.
And if the performance would be an issue, then it is an experience which will push the users to another infrastructure or however.
But allowing these other users to understand and use this good product.

I don't see any risk on your side, I am just seeing more users which would use HA...


Thanks and regards,

Gerhard

**Comment by frenck** [comment]
> Therefore I want to ask you to discuss internally about this topic.

That has been done already. It is not supported.
