### ISSUE TITLE
homeassistant/qemuarm-homeassistant:2021.3.0 - exiting and is staying with the status created

### ISSUE THREAD

**Issue by gklank** [home-assistant/docker-base#119]
Hi

The homeassistant/qemuarm-homeassistant:2021.3.0 is started automatically via the armhf-hassio-supervisor but exiting after 30-40 seconds with the error message below:

Error response from daemon: Cannot restart container cfee19a8d397: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/share/Container/Home_Assistant/HASS/tmp/homeassistant_pulse" to rootfs at "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/84a760e3fd95a3f1d06c6a9c4c345a36c84ac40d4116449bc73bd9ef2b4b5a90/merged/etc/pulse/client.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

Are there any ideas how to fix?

Regards,

Gerhard

**Comment by pvizeli** [comment]
wrong repo
