### ISSUE TITLE
Base images as muli-plattform images

### ISSUE THREAD

**Issue by Poeschl** [home-assistant/docker-base#134]
I'm discovering the docker multi-plattform option right now. I also thought about migrating my addons to just one final image with multi-plattform support.

This leads to the question for the base-images: Are there any plans to publish multi-plattform base images?

**Comment by frenck** [comment]
> Are there any plans to publish multi-plattform base images?

Add-ons won't work like that. For example, the Supervisor will pick the right images (including fallback) based on board/machine type. That is something Docker can't do. For that reason add-ons have an image per architecture. There is no benefit in publishing a meta image, as a matter of fact, there are still bugs in Docker that will affect us if we did.

**Comment by Poeschl** [comment]
Thanks for the fast answer @frenck 👍
