### ISSUE TITLE
Alpine Linux versions EOL and Release

### ISSUE THREAD

**Issue by Delta1977** [home-assistant/docker-base#141]
Hi, 
 Alpine Linux 3.10 is since 2021-05-01 EOL
 Alpine Linux 3.14 was released on 2021-06-15
 
so readme.md and other thinks jere are outdated

**Comment by ludeeus** [comment]
https://github.com/home-assistant/docker-base/releases/tag/2021.07.0

**Comment by Delta1977** [comment]
👍
