### ISSUE TITLE
Consider adding coreutils to images

### ISSUE THREAD

**Issue by Shaun-Harrison** [home-assistant/docker-base#153]
Hello!

I've been using scripts within home assistant to do various things - I've become stuck when trying to use the -d argument with date 

Turns out it's because coreutils is not installed on the home assistant images

I've got around this for now by creating a dockerfile to add it in , but this means that I will no longer get automatic updates (using watchtower) and will have to build an image each time a new release comes out

**Comment by frenck** [comment]
Could you describe the use case for it?
The container is not really meant as a command-line environment.

**Comment by Shaun-Harrison** [comment]
Ignore this

While running the modified image there appeared to be many issues with integrations

The use case btw was I'm hitting a API in a bash script, where I want to get a date range, so was using `date -dlast-monday` to get last mondays date

This doesn't work without the mentioned package, but using `date -d "-$24:00:00"` so I've modified the script to use this
