### ISSUE TITLE
s6 issues with 2022.05.1 Alpine base image

### ISSUE THREAD

**Issue by chrisx8** [home-assistant/docker-base#171]
It appears that the latest Alpine base image (tagged `2022.05.1` on Git) includes a broken version of `s6`. The symptoms would appear as some seemingly random permission issues.

For example, if I attempt to build the Tailscale community add-on with
```
BUILD_FROM=home-assistant/amd64-base:latest
```

The resulting image would not be able to start `tailscaled` due to permission issues. Here's the output:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun tailscaled (no readiness notification)
s6-supervise tailscaled (child): fatal: unable to exec run: Permission denied
s6-supervise tailscaled: warning: unable to spawn ./run - waiting 10 seconds
^Cs6-rc: warning: received INT, aborting longrun transitions and exiting asap
s6-rc: warning: unable to start service legacy-services: command crashed with signal 2
```

However, if I use the [`2022.05.0` image](https://github.com/home-assistant/docker-base/pkgs/container/amd64-base/21658368) with
```
FROM ghcr.io/home-assistant/amd64-base@sha256:f6b67206817445082fff84b17a35da6c5f83592ec6a4d4c2496a2a99225dff84
```
The resulting image behaves as expected.

Based off of the release notes, there might be an issue with `s6-overlay` and/or `Jemalloc`, as these are the only relevant things that have been updated.

**Comment by frenck** [comment]
> s6-supervise tailscaled (child): fatal: unable to exec run: Permission denied

Please read: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images
