### ISSUE TITLE
Can some sort of semver-like version be added to image tags?

### ISSUE THREAD

**Issue by deviantintegral** [home-assistant/docker-base#176]
The PR at https://github.com/home-assistant/docker-base/pull/166 updated to a new version of s6, which requires changes to addon configuration. Unfortunately, this means that previous commits of addons using base images such as `ARG BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.14` will no longer work without modification.

I know it may be too late now for this specific issue, but it would be good if this experience could be improved in the future. Ideas include:

1. Add a simple `-1`... `-2` suffix to image tags. Most versions would only ever have `-1`, but in this case the base image tag with s6 3.x could have been `3.14-2`, and noted on the README.
2. If there aren't too many similar compatibility changes over the lifecycle of an Alpine release, it could be named after the upgraded subsystem such as `3.14-s6v3`, becoming the default in the next major Alpine release.
3. If compatibility is not expected, then the README should make that clear so downstream authors know to use sha hashes instead of image tags if they wish.

**Comment by frenck** [comment]
We could do something like that in the future if needed / we need to make such a breaking change again.

Right now, there is no direct need for it (as this has been out for a bit already and damage was already done).

Therefore, will close this for now. 

PS: You could also use SHAs in your version specifier, that will avoid issues like this too. Dependabot will actually support updating this for you.
