### ISSUE TITLE
Would it be possible to support non s6-overlay images?

### ISSUE THREAD

**Issue by onedr0p** [home-assistant/docker-base#184]
Hi 👋🏼 

It would be great if your images could support a non s6-overlay container as well, maybe something like `homeassistant/home-assistant:2022.6.1-nonroot` ? From what I can gather, there isn't any need to have s6-overlay since there is only one process running in this container anyways: `python3 -m homeassistant --config /config`

Having s6-overlay is a security issue because the container is running as root, even if you use PUID/PGID to drop root permissions right before the application launches this could also be view as a security threat. Having a good security posture and following [container best practices](https://sysdig.com/blog/dockerfile-best-practices/) is important IMO.

```
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   15 root      0:00 s6-supervise s6-linux-init-shutdownd
   17 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   22 root      0:00 s6-supervise s6rc-oneshot-runner
   23 root      0:00 s6-supervise s6rc-fdholder
   30 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/
   59 root      0:00 s6-supervise home-assistant
   60 root      1h54 python3 -m homeassistant --config /config
   96 root      0:00 /bin/sh
  102 root      0:00 ps
```

What benefits do you all find in using s6, maybe there is something I am not aware of?

**Comment by frenck** [comment]
You can use any image you want, our base images use S6, if you like something different, that is up to you 👍 

../Frenck

**Comment by frenck** [comment]
Many things related to discovery are other examples (e.g., DHCP discovery).

You are free to use/run Home Assistant however you like, but we (as a project) have no interest in supporting was is suggested. This has been extensively discussed with the whole core team. The decision has been made and documented in our ADR records.
