### ISSUE TITLE
gammu dependecies missing for SMS integration

### ISSUE THREAD

**Issue by JanZimmer** [home-assistant/docker-base#188]
Related to core Issue: https://github.com/home-assistant/core/issues/75549

The SMS integration uses the gammu backend that is currently not present in the Docker containers. I myself use the Alpine based ones and installing the following packages was sufficient (ignore the python dep, this is done in the other issue).

I'd even contribute this myself but didn't find any contribution guide so I'm not sure which containers should be adapted in which way to add more dependencies to them and also. Also I'm not sure if gammu is available for all distros/architectures.

```
apk add gammu-dev gammu gammu-smsd
pip3 install python-gammu==3.2.3
```

**Comment by frenck** [comment]
This is not the right repository :)

Let's continue the conversation in the original core issue.
