### ISSUE TITLE
Latest version in README.md doesn't match tags

### ISSUE THREAD

**Issue by jak119** [home-assistant/docker-base#205]
The [README says that 3.17](https://github.com/home-assistant/docker-base/blob/77fae620ab8d438c288c7c992059aab71b956c15/README.md?plain=1#L16) is an available tag, but when you look at the actual image [aarch64-base](https://github.com/home-assistant/docker-base/pkgs/container/aarch64-base) for example 3.16 is the latest.

**Comment by frenck** [comment]
That is correct, you are viewing the development branch.

If you look at code on GitHub, you are looking at what is in progress.

See the releases in this repository for changes and availability.

../Frenck

**Comment by jak119** [comment]
Got it, thanks for the clarification!
