### ISSUE TITLE
Bashio is not available from debian image

### ISSUE THREAD

**Issue by lordrak007** [home-assistant/docker-base#207]
Hello,
i am trying create new addon which reckquires debian base image because program need gcc installed. So i cant use Alpine image.

My build.yaml contains only
build_from:
  amd64: homeassistant/amd64-base-debian:latest

My Docker file:
ARG BUILD_FROM
#FROM $BUILD_FROM

FROM alpine:3.15 as downloader
ARG RPORT_VERSION=0.9.5
RUN apk add unzip sqlite nmap-ncat apache2-utils tar
WORKDIR /app/
RUN set -e \
    && wget https://github.com/cloudradar-monitoring/rport/releases/download/0.9.5/rportd_0.9.5_Linux_x86_64.tar.gz -O rportd.tar.gz && tar xzf rportd.tar.gz rportd

#FROM debian:11
FROM $BUILD_FROM

COPY --from=downloader /app/rportd /usr/local/bin/rportd
COPY --from=downloader /app/frontend/ /var/www/html/
COPY --from=downloader /app/novnc/ /var/lib/rport-novnc

COPY entrypoint.sh /entrypoint.sh

RUN set -e \
    && useradd -d /var/lib/rport -m -U -r -s /bin/false rport \
    && mkdir -p /etc/rport && chown rport:rport /etc/rport
USER rport
COPY --chown=rport:rport rportd.conf.template /etc/rportd.conf.template
VOLUME [ "/var/lib/rport/" ]
ENTRYPOINT [ "/bin/bash", "/entrypoint.sh", "/usr/local/bin/rportd", "--data-dir", "/var/lib/rport", "--config", "/etc/rport/rportd.conf" ]

And entrypoint.sh:
#!/usr/bin/with-contenv bashio

conf_file=/etc/rport/rportd.conf
echo "Composing config for rport ..."
bashio::log.info "con file location: ${conf_file}"

exec "$@"

Plugin instals without error but after start it, i am getting error: /entrypoint.sh: line 18: bashio::log.info: command not found
So bashio does not accessible.

How please i can use bashio which may be alleady installer in source image?
Thank you

**Comment by frenck** [comment]
> homeassistant/amd64-base-debian:latest

Don't ever use `latest`, it doesn't mean what you think it does.

../Frenck
