### ISSUE TITLE
Docker Hub links for README / Docs

### ISSUE THREAD

**Issue by sepulworld** [home-assistant/docker-base#72]
Hi! Would it be possible to share the docker hub links for these base images in the readme? Im having a hard time finding them.

**Comment by sepulworld** [comment]
Also, might be useful to put example usage of base images in https://developers.home-assistant.io/docs/hassio_addon_index. I don't see any clear examples of using a base image, for example if I want to write an add-on in Python how / where do I pull the image? If I can figure it out, I can help add to the docs. It is pretty unclear to me though presently

**Comment by frenck** [comment]
The builder automatically picks them up for the correct architecture.
In case you want to override the default, this can be done in a `build.json` file as documented here:

<https://developers.home-assistant.io/docs/hassio_addon_config#add-on-extended-build>

For manual runs:

<https://developers.home-assistant.io/docs/hassio_addon_testing#local-build>
