### ISSUE TITLE
Compilation of armv7 fails

### ISSUE THREAD

**Issue by da-anda** [home-assistant/docker-base#73]
Hi, I have create an add-on that a couple people use by now. It is located here
https://github.com/da-anda/hass-io-addons/

I'm not sure what is responsible for the add-on not compiling anymore, but since I haven't changed the basic build script in ages and it stopped compiling on my RPI4 running HomeAssistant 0.110.1 I am kind of clueless and suppose it either might be an issue in HA 0.110 or something that changed in the baseimage? I am able to compile the docker image in a Ubuntu VM using the arm64 base image. Trying to compile the very same add-on version/config natively on my RPI4 fails with
```
20-05-22 11:53:47 ERROR (SyncWorker_16) [supervisor.docker.addon] Can't build local/armv7-addon-knxd:0.3.5: The command '/bin/ash -o pipefail -c set -xe     && apk update     && apk add --no-cache --virtual .build-dependencies                 build-base                 gcc                 git                 abuild                 binutils                 automake                 autoconf                 libtool                 argp-standalone                 linux-headers                 libev-dev                 libusb-dev                 cmake                 dev86      && apk add --no-cache                 udev                 libusb                 libev      && git clone --branch "${KNXD_VERSION}" --depth 1 https://github.com/knxd/knxd.git      && cd knxd      && ./bootstrap.sh      && ./configure --disable-systemd --enable-tpuart --enable-usb --enable-eibnetipserver --enable-eibnetip --enable-eibnetserver --enable-eibnetiptunnel      && mkdir -p src/include/sys && ln -s /usr/lib/bcc/include/sys/cdefs.h src/include/sys      && make      && make install 	 && make clean 	 && cd .. 	 && rm -rf knxd      && apk del --purge .build-dependencies' returned a non-zero code: 2
```
I already tried to compile it with only `apk update` as command (which resulted in `/bin/ash -o pipefail -c apk update`) but ended up with the very same error. I am out of ideas and as already mentioned, the only explanation for me would be an issue with the base image or a breaking change in HA. I also already tried the `hassio-builder` which didn't like my repo for some reason (docker complained about a wrong tag param but I don't see any difference in my config.json or build.json compared to f.e. duckdns add-on which compiled just fine).
I am sorry if this is the wrong place for this bug report/issue, but I didn't know where else to ask. The "test" branch is the most recent one which I would like to release, if you would like to give it a try compiling it yourself, but master also stopped working. Thank you.

**Comment by frenck** [comment]
Could you provide the output of a build done with either the docker commandline or the builder we provide?

Thanks 👍

**Comment by da-anda** [comment]
the builder gives me this when I try to build from the repo
https://paste.kodi.tv/wusapolohu.log

and trying to compile the image directly on the RPI4 via SSH to the host OS gives me this:
https://paste.kodi.tv/uzopuhadub.log

so it seems HomeAssistant is unable to fetch the image on the PI? Any idea why? I am running the AddGuard add-on on the same device, but it uses my FritzBox as "remote" DNS and the FritzBox is also DHCP. I can download the Alpine tar files just fine from my browser.

**Comment by da-anda** [comment]
@frenck any idea? Tried to compile another add-on on device with the same issue.

**Comment by IceEyz** [comment]
> the builder gives me this when I try to build from the repo
> https://paste.kodi.tv/wusapolohu.log

Your config.json doesn't specify a Docker repository for the image. Add "image": "dockerrepo/my-custom-addon" to your config.json or add the commandline arguments --docker-hub and --image. That worked out for me the other day, or actually, today :).

The error on your RPI4 is still indicative of a DNS resolution problem for which I have no clue.

**Comment by da-anda** [comment]
@IceEyz thanks, adding the `image` config fixed the tag issue, but it still won't compile https://paste.kodi.tv/erekipodul.kodi .  I tried all suggestions for a fix that I found on stackoverflow, even completely reinstalling docker and purging everything, but I keep getting this error. Do you by chance have any idea?

PS: sorry for using this ticket to continue asking for a now seemingly unrelated issue to the docker-base image

**Comment by IceEyz** [comment]
Perhaps you can try using the host docker instead of docker-in-docker. Add "-v /var/run/docker.sock:/var/run/docker.sock:ro" to your command.

**Comment by da-anda** [comment]
that seems to work. Thanks. So now only on-device compilation/docker installation is an issue. But as this is unrelated to docker-base I close my ticket again. Thanks for your help.
