### ISSUE TITLE
There is no python image for architecture armv7?

### ISSUE THREAD

**Issue by tonyldo** [home-assistant/docker-base#92]
There is no python image for architecture armv7 listed here:
https://github.com/home-assistant/docker-base#python-images
I made a hassio addon using this images, but figure out that didnt work with rasp pi 4 enviorement.
`20-10-05 21:03:47 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build aab028cf/armv7-addon-ttlock2mqtt:0.2: The command '/bin/ash -o pipefail -c pip3 install -r /tmp/requirements.txt' returned a non-zero code: 127`

**Comment by pvizeli** [comment]
I add it to readme. However, return 127 is no arch issue
